### ISSUE TITLE
如何使用呢

### ISSUE THREAD

**Issue by sssssshf** [Anything-of-anything/Anything-3D#2]
您好，感谢您的工作作出的贡献。我有两个问题想请教您：
1 所选的目标是不限的吗？
2 我应该如何使用您的项目 在自己的计算机上进行推理呢？

**Comment by Adamdad** [comment]
Dear @sssssshf ,

We greatly appreciate your interest. We are pleased to announce that our code has been recently released and is now available at https://github.com/Anything-of-anything/Anything-3D/tree/main/AnyObject3D. We kindly invite you to take a look.

For your question:
1. We intend to make it for any object in the wild, but we do find some corner cases that fails. You can have a try, but no full guarantee on the results.
2. Please see the code.

Best regards,
