### ISSUE TITLE
HRN demo

### ISSUE THREAD

**Issue by YiChenCityU** [Anything-of-anything/Anything-3D#3]
Hi, amazing project. However, the code of HRN is not released yet, how did you test it?

**Comment by Anything-of-anything** [comment]
Dear @YiChenCityU ,
Actually, they have released the code on a Chinese platform. https://www.modelscope.cn/models/damo/cv_resnet50_face-reconstruction/summary. Hope you enjoy it.
best

**Comment by YiChenCityU** [comment]
@Anything-of-anything Thanks very much.
