### ISSUE TITLE
大佬，具体实现开源么

### ISSUE THREAD

**Issue by CangHaiQingYue** [Anything-of-anything/Anything-3D#4]
如题，感谢大佬！

**Comment by Adamdad** [comment]
开源的，我们马上。正在考试周。这周之内开源♥️

**Comment by huanyu233** [comment]
泰酷辣！！！俺想加入，研一

**Comment by CangHaiQingYue** [comment]
> 开源的，我们马上。正在考试周。这周之内开源♥️

哈哈哈，期待~！
感谢！

**Comment by Ailyth99** [comment]
期待开源，真想试试

**Comment by momei123** [comment]
请问.mtl文件代码可以生成吗？

**Comment by sunqing-code** [comment]
期待开源

**Comment by Adamdad** [comment]
Dear @mocosun @CangHaiQingYue @momei123 @sunqing-code @Ailyth99 ,

We greatly appreciate your interest. We are pleased to announce that our code has been recently released and is now available at https://github.com/Anything-of-anything/Anything-3D/tree/main/AnyObject3D. We kindly invite you to take a look.

Best regards,
